import Head from "next/head";

const Default = ({children}) => {
  console.log(children);
  return (
    <>
      <Head>
        <title>ASMR Hub 1.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{children}</main>
      
    </>
  );
};

export default Default;
