import { useEffect } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Sidebar from "../components/Sidebar";
import SidebarMobile from "../components/SidebarMobile";
import {
  CashIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  OfficeBuildingIcon,
  SearchIcon,
} from "@heroicons/react/solid";

const Default = ({ children }) => {
  return (
    <>
      <Head>
        <title>IoT Device Management - {children.props.componentName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <div className="min-h-full">
        <Sidebar componentName={children.props.componentName} isOpen={false} />
        <div className="lg:pl-64 flex flex-col flex-1">
          <div className="relative z-10 flex-shrink-0 flex h-16 border-b border-gray-200 lg:border-none">
            <SidebarMobile componentName="Devices" />
            {/* Search bar */}
            {/* <Header /> */}
          </div>
          {children}
        </div>
      </div>
    </>
  );
};

export default Default;
Default.Auth = true;