// export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
// export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
// export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";
// export const CART_QUANTITY_INCREASE = "CART_QUANTITY_INCREASE";
// export const CART_QUANTITY_DECREASE = "CART_QUANTITY_DECREASE";
// export const FILTER_PRODUCTS = "FILTER_PRODUCTS";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const FETCH_USER = "FETCH_USER";


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
